# Maintained by @riddance/env
FROM node:18.18-alpine3.18

RUN mkdir /app
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --progress false

COPY . /app

ENTRYPOINT ./node_modules/.bin/riddance-build
